site:
  
  title: INEX Documents
  start_page: Documents::index.adoc
content:
  sources:
  - url: https://github.com/zvulun/inexsources-repo.git
    branches: HEAD
    start_path: docs
    version:

antora:
  extensions:
    - '@antora/lunr-extension'

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: ./supplemental_ui
  # - path: ui.yml
    # contents: |
      # static_files:
      # - .nojekyll
  - path: .nojekyll
