site:
  #This comment can be changed, saved, added, committed and pushed
  #to trigger github actions to generate your online site
  title: Documents
  start_page: Documents::index.adoc
content:
  sources:
  - url: https://github.com/zvulun/inexsources-repo.git
    branches: HEAD
    start_path: docs
    version: [Latest]

antora:
  extensions:
    - '@antora/lunr-extension'

asciidoc:
  attributes:
    sectnums: all
    sectnumlevels: 4
    toclevels: 3
    xrefstyle: full
    short-compname: INEX@
    med-compname: INEX/TECH@
    long-compname: INEX Technologies@
    long-possess-compname: INEX Technologies'@

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental_ui
  # - path: .nojekyll
