site:
  
  title: Documents
  start_page: Documents::index.adoc
content:
  sources:
  - url: C:\inexsources-repo\
    branches: HEAD
    start_path: docs
    version: [Latest]

antora:
  extensions:
    - '@antora/lunr-extension'

asciidoc:
  attributes:
    sectnums: all
    sectnumlevels: 4
    toclevels: 3
    xrefstyle: short
    #If you add an attribute to this playbook,
    #be sure to add it to the (non-local) antora-playbook file.

    #These attributes are not for use in the
    #zAsciiDocMultipleNameReplace macro; they are
    #for reuse in the specification tables
    #on rows that might change
    lpr-analytics: Plate Recognition, State of Issue, Type
    vehicle-analytics: Vehicle Detection, Classification, Color, Make; Vehicle Without Plate
    iza-weight: 9.0 lbs (4.1 kg)

    #These attributes control substitutions in
    #parts of the text which are very similar, but
    #have small changes based on the product
    #or type of document. They are just mentioned here
    #but not set, so that the default will be unset
    #and only the relevant one will be set
    #at the start of the document
    #xref-type-RoadView:
    #xref-type-IZA800G:
    #xref-type-IZA800GVES:
    #xref-type-IZA500G:
    #xref-type-IZ600F:
    #xref-type-IZIDPUG:
    #layout-type-userguide:
    #layout-type-technote:
    #link-type-gdrive:
    #link-type-site:


    #Put attributes whose string values have letters in
    #common with other similar values in order of longest
    #value to shortest value. This will prevent the replacement
    #macros from replacing the shorter strings that are within
    #the longer strings.
    #The @ at the end of each value indicates that
    #these are soft-set attributes, which can
    #be overridden in individual files if needed.

    #if you add any attributes to this list
    #be sure to add them to the text file used to
    #replace strings with attributes, accessed by the
    #zAsciiDocMultipleNameReplace macro

    compname-possess: INEX Technologies'@
    compname-long: INEX Technologies@
    compname-med: INEX/TECH@
    compname-short: INEX@

    camera-DOT: IZA800GDOT@
    camera-ORT: IZA800GORT@
    camera-VES: IZA800GVES@
    camera-GRV: IZA800GRV@
    camera-5G: IZA500G@
    camera-5GR: IZA500GR@
    camera-DFC: IZA500GDFC@
    camera-8G: IZA800G@
    camera-6F: IZ600F@
    camera-B6F: IZB600F@

    mount-black-arm: MNT-W3X@

    kit-DFC-1L: IZA500DFC-1L@
    software-DFC-1S: IZCLOUD-DFC-1S@
    software-DFC-1C: IZCLOUD-DFC-1C@

    software-server: IZCentral@
    software-cloud: IZCloud@
    software-discovery: IZ Discovery@
    software-discovery-nospace: IZDiscovery@
    software-ALPR-long: RoadView ALPR@
    software-ALPR: RoadView@
    software-monitoring: IZMonitoring Server@
    hw-iocontroller: IZIO@
    hw-poeinjector: IZ4POE@
    hw-connection-panel: IZPanel@
    hw-webrelay-quad: IZ-REM-RELAY-4@
    hw-webrelay-single: IZ-REM-RELAY@
    hw-indoor-processor: IZIDPUG@
    hw-outdoor-processor: IZODPUG@
    hw-loopdetect-l: LOOP-DTCR-L@
    hw-loopdetect-p: LOOP-DTCR-P@

    illum-strobe: IZS@
    illum-non-strobe: IZL@
    illum-VES: IZSVES@
    illum-DFC: IZS2DFC@
    system-type: ALPR@
    generic-camera-name: ALPR Camera System@

    eyesafetystandard-1: IEC62471 Group 1@
    eyesafetystandard-2: IEC62471 Group 2@
    eyesafetystandard-3: IEC62471 Group 3@
    eyesafetystandard-short-1: IEC62471@

    #if you add any attributes to this list above
    #be sure to add them to the text file used to
    #replace strings with attributes, accessed by the
    #zAsciiDocMultipleNameReplace macro

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental_ui
  # - path: .nojekyll
